# Generated by Django 6.0.3 on 2026-06-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangarinapp', '0004_note_user_subtask_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='user',
        ),
    ]
